services:
  electrumx:
    image: electrumx-plm:local
    container_name: electrumx-plm
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "50001:50001"  # TCP
      - "50002:50002"  # SSL

    environment:
      COIN: "Palladium"
      NET: "mainnet"

      DAEMON_URL: "http://<rpcuser>:<rpcpassword>@host.docker.internal:2332/"  # RPC credentials

      SERVICES: "tcp://0.0.0.0:50001,ssl://0.0.0.0:50002"

      SSL_CERTFILE: "/certs/server.crt"
      SSL_KEYFILE: "/certs/server.key"

      DB_DIRECTORY: "/data"
      PEER_DISCOVERY: "off"
      PEER_ANNOUNCE: "false"
      INITIAL_CONCURRENT: "2"
      COST_SOFT_LIMIT: "0"
      COST_HARD_LIMIT: "0"

    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576

    volumes:
      - ./data:/data